---
# this is a place-holder workflow in order to align action workflow to the overall CI process

name: re-build-test

on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      ARTIFACT_ID:
        value: ${{ jobs.build.outputs.ARTIFACT_ID }}

      BUILD_VERSION:
        value: ${{ jobs.build.outputs.BUILD_VERSION }}

      WORKFLOW_RUN_ID:
        value: ${{ jobs.build.outputs.WORKFLOW_RUN_ID }}


  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.x'

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      # ARTIFACT_ID and WORKFLOW_RUN_ID are here to align to the current CI validate-release job requirements
      ARTIFACT_ID: '000-111-222'
      WORKFLOW_RUN_ID: '000-111-333'
      BUILD_VERSION: ${{ steps.set-build-version.outputs.BUILD_VERSION }}

    steps:

    - name: Checkout source code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Commitizen
      run: pip install -U commitizen

    # set and get build version
    - name: Set Build Version
      id: set-build-version
      run: |
        echo "BUILD_VERSION=$(cz version -p)" >> "$GITHUB_OUTPUT"

    - name: Get Build Version
      id: get-build-version
      run: |
        echo "Build Version: ${{ steps.set-build-version.outputs.BUILD_VERSION }}"
